### ISSUE TITLE
Issue while preprocessing CANRAD data using download.sh

### ISSUE THREAD

**Issue by mriganktiwari** [microsoft/ContextualSP#13]
I am getting this error while running ```download.sh``` script:

```
--2021-12-19 22:06:48--  https://obj.umiacs.umd.edu/elgohary/CANARD_Release.zip
Resolving obj.umiacs.umd.edu (obj.umiacs.umd.edu)... 128.8.122.11
Connecting to obj.umiacs.umd.edu (obj.umiacs.umd.edu)|128.8.122.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3258983 (3.1M) [application/zip]
Saving to: ‘CANARD_Release.zip’

CANARD_Release.zip                           100%[============================================================================================>]   3.11M   458KB/s    in 7.0s

2021-12-19 22:06:57 (458 KB/s) - ‘CANARD_Release.zip’ saved [3258983/3258983]

Archive:  CANARD_Release.zip
replace ._CANARD_Release? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ._CANARD_Release
  inflating: multiple_refs.json
replace ._multiple_refs.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ._multiple_refs.json
  inflating: test.json
replace ._test.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ._test.json
  inflating: dev.json
replace ._dev.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ._dev.json
  inflating: train.json
replace ._train.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ._train.json
  inflating: readme.txt
replace ._readme.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ._readme.txt
Traceback (most recent call last):
  File "../../preprocess.py", line 197, in <module>
    unified_dataset_format("Multi")
  File "../../preprocess.py", line 85, in unified_dataset_format
    src_f = open(src_file, "r", encoding="utf8")
FileNotFoundError: [Errno 2] No such file or directory: 'train.sr'
```

**Comment by mriganktiwari** [comment]
I was able to fix it
